# Generated by Django 6.0 on 2025-12-03 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(help_text='Порядок внутри круга (1 – ночь, 2 – день и т.п.)')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_unique', models.BooleanField(default=False)),
                ('turn_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('active', 'Идёт'), ('finished', 'Завершена')], default='planned', max_length=20)),
                ('players_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='game.mode')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_side', models.CharField(choices=[('mafia', 'Мафия'), ('town', 'Мирные')], max_length=10)),
                ('rounds_count', models.IntegerField()),
                ('mafia_count', models.IntegerField()),
                ('town_count', models.IntegerField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='game.session')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('alive', 'В игре'), ('dead', 'Выбыл')], default='alive', max_length=10)),
                ('seat_number', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('fail_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_players', to='game.phase')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='game.role')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.session')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(help_text='Номер круга/дня')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='game.phase')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.session')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='game.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_votes', to='game.player')),
            ],
        ),
    ]
