# Generated by Django 6.0 on 2025-11-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mode',
            options={'ordering': ['id'], 'verbose_name': 'Режим игры', 'verbose_name_plural': 'Режимы игры'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['order'], 'verbose_name': 'Фаза игры', 'verbose_name_plural': 'Фазы игры'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['session', 'seat_number', 'name'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Результат партии', 'verbose_name_plural': 'Результаты партий'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at'], 'verbose_name': 'Игровая сессия', 'verbose_name_plural': 'Игровые сессии'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['session', 'round_number'], 'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterField(
            model_name='mode',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='max_players',
            field=models.PositiveIntegerField(verbose_name='Максимум игроков'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='min_players',
            field=models.PositiveIntegerField(verbose_name='Минимум игроков'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название режима'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название фазы'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='order',
            field=models.PositiveIntegerField(help_text='1 – ночь, 2 – день, 3 – голосование и т.п.', verbose_name='Порядок в круге'),
        ),
        migrations.AlterField(
            model_name='player',
            name='fail_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_players', to='game.phase', verbose_name='Фаза выбывания'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя в партии'),
        ),
        migrations.AlterField(
            model_name='player',
            name='notes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='game.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='player',
            name='seat_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер места за столом'),
        ),
        migrations.AlterField(
            model_name='player',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('alive', 'В игре'), ('dead', 'Выбыл')], default='alive', max_length=10, verbose_name='Статус игрока'),
        ),
        migrations.AlterField(
            model_name='result',
            name='mafia_count',
            field=models.PositiveIntegerField(verbose_name='Количество мафии'),
        ),
        migrations.AlterField(
            model_name='result',
            name='rounds_count',
            field=models.PositiveIntegerField(verbose_name='Количество кругов'),
        ),
        migrations.AlterField(
            model_name='result',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='game.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='result',
            name='town_count',
            field=models.PositiveIntegerField(verbose_name='Количество мирных'),
        ),
        migrations.AlterField(
            model_name='result',
            name='winner_side',
            field=models.CharField(choices=[('mafia', 'Мафия'), ('town', 'Мирные')], max_length=10, verbose_name='Победившая сторона'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_unique',
            field=models.BooleanField(default=False, verbose_name='Уникальная роль'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='role',
            name='turn_order',
            field=models.PositiveIntegerField(blank=True, help_text='Чем меньше число, тем раньше ходит роль в ночной фазе', null=True, verbose_name='Порядок хода'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='session',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='session',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ведущий'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='game.mode', verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='session',
            name='players_count',
            field=models.PositiveIntegerField(verbose_name='Количество игроков'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('active', 'Идёт'), ('finished', 'Завершена')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='game.phase', verbose_name='Фаза'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='round_number',
            field=models.PositiveIntegerField(help_text='Номер игрового круга/дня', verbose_name='Номер круга'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='game.player', verbose_name='Цель голосования'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_votes', to='game.player', verbose_name='Голосующий'),
        ),
    ]
