# Generated by Django 6.0 on 2025-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_mode_options_alter_phase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['session', 'number', 'seat_number', 'name'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер игрока в сессии'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('session', 'number'), name='unique_player_number_per_session'),
        ),
    ]
