# Generated by Django 6.0 on 2025-11-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_options_player_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_player_number_per_session',
        ),
    ]
