# Generated by Django 6.0 on 2025-12-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_player_unique_player_number_per_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['session', 'seat_number', 'name'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
    ]
