# Generated by Django 6.0 on 2025-11-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_player_options_remove_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_in_phase', to='game.phase', verbose_name='Текущая фаза'),
        ),
        migrations.AddField(
            model_name='session',
            name='current_round',
            field=models.PositiveIntegerField(default=1, verbose_name='Текущий круг'),
        ),
    ]
