# Generated by Django 6.0 on 2025-11-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_session_current_phase_session_current_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='game.role', verbose_name='Роль'),
        ),
    ]
