# Generated by Django 6.0 on 2025-11-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fail_round',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Круг выбывания'),
        ),
    ]
