# Generated by Django 6.0 on 2025-11-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('host', 'Ведущий'), ('player', 'Игрок')], default='player', max_length=20, verbose_name='Роль'),
        ),
    ]
