# Generated by Django 6.0 on 2025-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_profile_options_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('active', 'Идёт'), ('finished', 'Завершена'), ('cancelled', 'Сброшена')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
